# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Azure Pipelines

steps:
- task: NodeTool@0
  displayName: 'install nodejs'
  inputs:
    versionSpec: 10.x

- task: Npm@1
  displayName: 'install dependencies'
  inputs:
    command: ci
    workingDir: '$(system.defaultworkingdirectory)'
    verbose: false

- task: Npm@1
  displayName: 'validate we can create vsix'
  inputs:
    command: custom
    workingDir: '$(system.defaultworkingdirectory)'
    verbose: false
    customCommand: 'run package'

- task: CopyFiles@2
  displayName: 'copy sources'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **/*
     !**/*.vsix
     !node_modules/**
     !out/**
     !.git/**
     !dist/**
     !.vscode/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)/source'

- task: PublishBuildArtifacts@1
  displayName: 'publish source'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/source'
    ArtifactName: source


- task: CopyFiles@2
  displayName: 'copy vsix'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/vsix'
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'publish vsix'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/vsix'
    ArtifactName: vsix
  enabled: false