parameters:
  jobName: 'build'
  pool: ''
  publish: false

jobs:
- job: build
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-18.04'
      windows:
        imageName: 'windows-latest'
  pool: 
    vmImage: $(imageName)
  continueOnError: true
  steps:
  - task: NodeTool@0
    displayName: 'install nodejs'
    inputs:
      versionSpec: 10.x

  - task: Npm@1
    displayName: 'install dependencies'
    inputs:
      command: ci
      workingDir: '$(system.defaultworkingdirectory)'
      verbose: false

  - task: Npm@1
    displayName: 'validate we can create vsix'
    inputs:
      command: custom
      workingDir: '$(system.defaultworkingdirectory)'
      verbose: false
      customCommand: 'run package'

  - ${{ if eq(variables.imageName, 'windows-latest') }}:
    - task: CopyFiles@2
      displayName: 'copy sources'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: |
            **/*
            !**/*.vsix
            !node_modules/**
            !out/**
            !.git/**
            !dist/**
            !.vscode/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)/source'
      condition: eq('${{ parameters.publish }}', true)

    - publish: '$(Build.ArtifactStagingDirectory)/source'
      displayName: 'publish source'
      artifact: 'source'
      condition: eq('${{ parameters.publish }}', true)
      
