parameters:
  jobName: 'build'
  pool: ''
  publish: false

jobs:
- job: build
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-18.04'
      windows:
        imageName: 'windows-latest'
  pool: 
    vmImage: $(imageName)
  continueOnError: true
  steps:
  - task: Bash@3
    displayName: 'print variables'
    inputs:
      targetType: 'inline'
      script: 'env | sort'

  - task: NodeTool@0
    displayName: 'install nodejs'
    inputs:
      versionSpec: 10.x

  - task: Npm@1
    displayName: 'install dependencies'
    inputs:
      command: ci
      workingDir: '$(system.defaultworkingdirectory)'
      verbose: false

  - task: Npm@1
    displayName: 'validate we can create vsix'
    inputs:
      command: custom
      workingDir: '$(system.defaultworkingdirectory)'
      verbose: false
      customCommand: 'run package'

  - ${{ if eq('${{ parameters.publish }}', true) }}:
    - task: CopyFiles@2
      displayName: 'copy sources'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: |
            **/*
            !**/*.vsix
            !node_modules/**
            !out/**
            !.git/**
            !dist/**
            !.vscode/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)/source'

    - publish: '$(Build.ArtifactStagingDirectory)/source'
      displayName: 'publish source'
      artifact: 'source'