trigger:
  - master
  
pool:
    name: Azure Pipelines

stages:
  - stage: build
    displayName: build source
    jobs:
      - template: templates\build.yml
        parameters:
          publish: true
